openapi: "3.0.0"
info:
  version: ""
  title: ""
  description: ""
paths:
  /:
    get:
      summary: ""
      parameters: []
      description: ""
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetHomeResponse"
    post:
      summary: ""
      parameters: []
      description: ""
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostHomeResponse"
  /me:
    get:
      summary: ""
      parameters: []
      description: ""
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMeResponse"
  /me/{params1}/kiki/{params2}:
    get:
      summary: ""
      parameters:
        - name: "params1"
          in: "path"
          required: true
          description: ""
          schema:
            type: "string"
        - name: "params2"
          in: "path"
          required: true
          description: ""
          schema:
            type: "string"
      description: ""
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMeParams1KikiParams2Response"
servers:
  - url: "http://localhost:8000"
    description: "URL"
components:
  schemas:
    GetHomeResponse:
      additionalProperties: false
      properties:
        salut:
          type: "string"
      required:
        - "salut"
      type: "object"
    LEBodyDuPost:
      additionalProperties: false
      properties:
        dsad:
          type: "string"
      required:
        - "dsad"
      type: "object"
    PostHomeResponse:
      additionalProperties: false
      properties:
        leBodyDuPost:
          $ref: "#/components/schemas/LEBodyDuPost"
      required:
        - "leBodyDuPost"
      type: "object"
    GetMeResponse:
      additionalProperties: false
      properties:
        id:
          type: "string"
        nom:
          type: "string"
        prenom:
          type: "string"
      required:
        - "id"
        - "nom"
        - "prenom"
      type: "object"
    GetMeParams1KikiParams2Response:
      additionalProperties: false
      properties:
        id:
          type: "string"
        nom:
          type: "string"
        prenom:
          type: "string"
      required:
        - "id"
        - "nom"
        - "prenom"
      type: "object"
